version: "3"

volumes:
  mystuff-data:

networks:
  mystuff-net:

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_stuff
      MYSQL_USER: my_stuff
      MYSQL_PASSWORD: my_stuff
    volumes:
      - mystuff-data:/var/lib/mysql
    networks:
      mystuff-net:
        aliases:
            - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    networks:
      - mystuff-net
    depends_on:
      - mysql
  backend:
    image: my-stuff-backend:0.99.1
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - mystuff-net
    depends_on:
      - mysql
